### ISSUE TITLE
merge code from static repo

### ISSUE THREAD

**Issue by SwiftMike** [SwiftMike/hiigrade#32]

**Comment by SwiftMike** [comment]
merge code from hiigrade-local repository

**Comment by yoonslee** [comment]
We'll see if this is feasible during our next merge. I made the mistake of making different progress on each branch, and a merge may not be a good idea. I made a lot of styling progress on the local branch, but we may have to just re-do that since we're going with the persistent `plant-group` and `plant-group-yoon` branches.

**Comment by yoonslee** [comment]
Merged
